[project]
name = "calliopy"
version = "0.1.0"
description = "Visual novel framework with DI container"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "greenlet>=3.2.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
